import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../components/Header";
import Sidebar from "../components/sidebar";
import ItemList from "../components/itemList";
import styles from "../styles/Home.module.css";
import AddObj from "./api/stocks";
import { useState, useRef, useEffect } from "react";

export default function Home() {
  // 検索機能
  const [items, setItems] = useState([]);
  const [searchQuery, setSearchQuery] = useState([]);
  const [searchValue, setSearchValue] = useState<string | undefined>("");

  const handleSearch = (e: any) => {
    setSearchValue(e.target.value);
  };

  const handleClick = (e: any) => {
    e.preventDefault();
    setData(initializedData);
    setSearchQuery(
      items.filter((stock: any) =>
        stock.item.name.toLowerCase().includes(searchValue?.toLowerCase())
      )
    );
  };

  useEffect(() => {
    fetch("http://localhost:8000/stock")
      .then((res) => res.json())
      .then((data) => {
        setItems(data);
        setSearchQuery(data);
      });
  }, []);

  const initializedData = {
    notifyFrequency: "",
  };

  // カテゴリ絞り込み機能

  const [data, setData] = useState(initializedData);

  const handleFrequencyChange = (e: any) => {
    const newValue =
      e.target.value === data.notifyFrequency ? "" : e.target.value;
    const newData = { ...data, notifyFrequency: newValue };
    setData(newData);

    if (e.target.checked) {
      setSearchQuery(
        items.filter((stock: any) => e.target.value === stock.item.series)
      );
    } else {
      setSearchQuery(items);
    }
  };

  console.log(AddObj());
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href="/api/stock">リンク</Link>
        <div className={styles.mainFlex}>
          <Sidebar
            onChange={handleSearch}
            onClick={handleClick}
            data={data}
            handleFrequencyChange={handleFrequencyChange}
          />
          <div className={styles.gridBox}>
            <ItemList searchQuery={searchQuery} />
          </div>
        </div>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
